# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b63008f36afb5607b18326ff2776fe4d9f83c2df0958b9a7e1fde542848a0e697722128cded0bab05278503a4f81e0415f4e7bd35f224db70384a8da292042e9

test:
  secret_key_base: ec3f5a7ea9c369ef5089754a018940546b88cf7095905a4051087b5fd4a3fb8da89166ba357ba9b864239004137ddfaedc7b39ecf46ab2a1f29961dcf0b42a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
